### PR TITLE
Update to 0.3.0

### PR DESCRIPTION
**Pull request by andreasnoack**

### CODE REVIEW

**Comment by ViralBShah** [comment]
It's getting a hash mismatch.

**Comment by andreasnoack** [comment]
I'd computed it from the prerelease version instead of the actual release. I've corrected it. Let's see if it works.

**Comment by andreasnoack** [comment]
This seems to work now except that the Windows builds time out.

**Comment by ViralBShah** [comment]
Can we restart the build?

**Comment by staticfloat** [comment]
Thanks Andreas.

**Comment by staticfloat** [comment]
For the record, the windows builds have never completed on Travis; I always just build locally and upload the binaries manually.

**Pull request merged**
