### PR TITLE
Julia compatibility

### PR DESCRIPTION
**Pull request by staticfloat**
This should build libraries that are named the proper things for Julia compatibility.

### CODE REVIEW

**Comment by staticfloat** [comment]
@andreasnoack @ViralBShah I'm building the binaries locally and will upload them to a new release when I'm satisfied.

**Comment by ViralBShah** [comment]
JuliaLang Appveyor now has workers with 3 hour timeouts. Is there a way to somehow use that Appveyor account to make this fully automatic?

**Comment by staticfloat** [comment]
We don't build with Appveyor, we build with Travis.  We may be able to get a little faster with some small improvements to BinaryBuilder, but there will just always be some projects that we can't build completely on Travis, unfortunately.

**Comment by ViralBShah** [comment]
Yeah - I keep forgetting about the cross-compile.

**Pull request merged**
